# Import

In [212]:
import sys

import numpy as np

# Setup

In [213]:
# 

---

# Demo

> Desc.

---

# TOC

- [Numpy Arrays](#Numpy-Arrays)
- [Funtion](#Function)
    - [linspace](#linspace)
    - [random](#random)
    - [arange](#arange)
    - [reshape](#reshape)
    - [zeros](#zeros)
    - [ones](#ones)
    - [empty](#empty)
    - [identity](#identity)
    - [eye](#eye)
- [Size of objects in Memory](#Size-of-objects-in-Memory)
    - [Performance](#Performance)

---

# Numpy Arrays

In [214]:
na = np.array([1, 2, 3, 4])
nb = np.array([0, 0.5, 1, 1.5, 2])

In [215]:
print(na)
print(nb)

[1 2 3 4]
[0.  0.5 1.  1.5 2. ]


In [216]:
na[0], na[1]

(1, 2)

In [217]:
nb[0], nb[1]

(0.0, 0.5)

In [218]:
na[0:]

array([1, 2, 3, 4])

In [219]:
na[1:3]

array([2, 3])

In [220]:
na[:-1]

array([1, 2, 3])

In [221]:
na[::2]

array([1, 3])

In [222]:
nb[-1]

2.0

In [223]:
nb[[0, 2, -1]]

array([0., 1., 2.])

---

## Array Types

In [224]:
na

array([1, 2, 3, 4])

In [225]:
nb

array([0. , 0.5, 1. , 1.5, 2. ])

In [226]:
na.dtype

dtype('int32')

In [227]:
nb.dtype

dtype('float64')

#### Set Type

In [228]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [229]:
np.array([1, 2, 3, 4], dtype=np.int64)

array([1, 2, 3, 4], dtype=int64)

In [230]:
nc = np.array(["a", "b", "c"])

In [231]:
nc.dtype

dtype('<U1')

In [232]:
nd = np.array([{"a": 1}, sys])

In [233]:
nd.dtype

dtype('O')

#### Demo

In [234]:
level_list = np.array([1000, 4000, 150, 9001, 1500])
any(level_list > 9000)

True

---

## Dimensions and shapes

#### Demo

In [235]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [236]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [237]:
A.shape

(2, 3)

In [238]:
A.ndim

2

In [239]:
A.size

6

---

#### Demo

In [240]:
B = np.array(
    [
        [
            [12, 11, 10],
            [9, 8, 7],
        ],
        [[6, 5, 4], [3, 2, 1]],
    ]
)

In [241]:
B.dtype

dtype('int32')

---

#### Demo
If the shape isn't consistent, it'll just fall back to regular Python objects:



In [242]:
C = np.array(
    [
        [
            [12, 11, 10],
            [9, 8, 7],
        ],
        [[6, 5, 4]],
    ],
    dtype=np.object_,
)

In [243]:
C.dtype

dtype('O')

In [244]:
C.shape

(2,)

In [245]:
C.size

2

In [246]:
type(C[0])

list

---

## Indexing and Slicing of Matrices

In [247]:
# Square matrix
"""
# .  0  1  2
    [1, 2, 3],  # 0
    [4, 5, 6],  # 1
    [7, 8, 9],  # 2
"""
A = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

In [248]:
A[1]

array([4, 5, 6])

In [249]:
# A[d1, d2, d3, d4]
A[1][0]

4

In [250]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [251]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [252]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [253]:
A[:2, 2:]

array([[3],
       [6]])

In [254]:
A[1] = np.array([10, 10, 10])
A[2] = 99

In [255]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

---

## Summary Statistics

In [256]:
na

array([1, 2, 3, 4])

In [257]:
na.sum()

10

In [258]:
na.mean()

2.5

- 標準差(std, standard deviation)
- 變異數(var, variance)

In [259]:
na.std()

1.118033988749895

In [260]:
na.var()

1.25

In [261]:
D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [262]:
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [263]:
D.sum()

45

In [264]:
D.mean()

5.0

In [265]:
D.std()

2.581988897471611

- axis=None: Apply operation array-wise.
- 
axis=0: Apply operation column-wise, across all rows for each column
- 
axis=1: Apply operation row-wise, across all columns for each row.

In [266]:
D.sum(axis=0)

array([12, 15, 18])

In [267]:
D.sum(axis=1)

array([ 6, 15, 24])

In [268]:
D.mean(axis=0)

array([4., 5., 6.])

In [269]:
D.mean(axis=1)

array([2., 5., 8.])

## Broadcasting and Vectorized operations

In [270]:
ndarr = np.arange(4)

In [271]:
ndarr

array([0, 1, 2, 3])

In [272]:
ndarr + 10

array([10, 11, 12, 13])

In [273]:
ndarr * 10

array([ 0, 10, 20, 30])

In [274]:
ndarr

array([0, 1, 2, 3])

In [275]:
ndarr += 100
ndarr

array([100, 101, 102, 103])

In [276]:
l = [0, 1, 2, 3]

In [277]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [278]:
a = np.arange(4)
b = np.array([10, 10, 10, 10])

In [279]:
a + b

array([10, 11, 12, 13])

## Boolean Arrays

In [280]:
a = np.arange(4)

In [281]:
a[[True, False, False, True]]

array([0, 3])

In [282]:
a >= 2

array([False, False,  True,  True])

In [283]:
a[a >= 2]

array([2, 3])

In [284]:
a[a > a.mean()]

array([2, 3])

In [285]:
a[~(a > a.mean())]

array([0, 1])

In [286]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [287]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [288]:
K = np.random.randint(100, size=(3, 3))

In [289]:
K

array([[34, 17, 38],
       [65, 83, 10],
       [61, 70, 26]])

In [290]:
K > 30

array([[ True, False,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [291]:
K[K > 30]

array([34, 38, 65, 83, 61, 70])

## Linear Algebra


In [292]:
LA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [293]:
LB = np.array([[6, 5], [4, 3], [2, 1]])

- dot
- `@`
- `T`

In [294]:
LA.dot(LB)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [295]:
LA @ LB

array([[20, 14],
       [56, 41],
       [92, 68]])

In [296]:
LB.T

array([[6, 4, 2],
       [5, 3, 1]])

In [297]:
LB.T @ LA

array([[36, 48, 60],
       [24, 33, 42]])

---

# Function

### `random`

In [315]:
np.random.random(size=2)

array([0.92404567, 0.34414093])

In [317]:
np.random.normal(size=2)

array([-1.21242908,  0.41298576])

In [316]:
np.random.rand(2, 4)

array([[0.95568927, 0.64763469, 0.68806986, 0.54028216],
       [0.8501506 , 0.73901338, 0.22268109, 0.74608047]])

---

### `arrage`

In [320]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [321]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [325]:
np.arange(0, 2, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

---

### `reshape`
> Gives a new shape to an array without changing its data.

In [345]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [347]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

---

### `zeros`

In [358]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [360]:
np.zeros((3, 3), dtype=np.int_)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

---

### `ones`

In [364]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [363]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

---

### `empty`

In [366]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [365]:
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

---

### `identity`

In [312]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

### `eye`

In [314]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

### `linspace`
> 在一定範圍內來均勻地撒點

In [298]:
a = np.linspace(1, 3, 3)
print(a)

[1. 2. 3.]


In [299]:
a = np.linspace(1, 5, 20)
print(a)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [357]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### `Func`
> Desc.

---

# Size of objects in Memory



- An integer in Python is > 24bytes
- Longs are even larger
- Numpy size is much smaller

In [300]:
sys.getsizeof(1)

28

In [301]:
sys.getsizeof(10**100)

72

In [302]:
np.dtype(int).itemsize

4

In [303]:
np.dtype(np.int8).itemsize

1

In [304]:
np.dtype(float).itemsize

8

- Lists are even larger



In [305]:
sys.getsizeof([1])

64

In [306]:
np.array([1]).nbytes

4

## Performance

In [307]:
pl = list(range(100000))

In [308]:
na = np.arange(100000)

In [309]:
%time np.sum(na ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [310]:
%time sum([x ** 2 for x in pl])

CPU times: total: 15.6 ms
Wall time: 11 ms


333328333350000