# Import

In [80]:
import sys

import numpy as np

# Setup

In [81]:
# code

---

# Demo

> Desc.

---

# TOC

- [Numpy Arrays](#Numpy-Arrays)
- [Funtion](#Function)
    - [linspace](#linspace)
    - [random](#random)
    - [arange](#arange)
    - [reshape](#reshape)
    - [zeros](#zeros)
    - [ones](#ones)
    - [empty](#empty)
    - [identity](#identity)
    - [eye](#eye)
- [Size of objects in Memory](#Size-of-objects-in-Memory)

---

# Numpy Arrays

In [82]:
na = np.array([1, 2, 3, 4])
nb = np.array([0, 0.5, 1, 1.5, 2])

In [83]:
print(na)
print(nb)

[1 2 3 4]
[0.  0.5 1.  1.5 2. ]


In [84]:
na[0], na[1]

(1, 2)

In [85]:
nb[0], nb[1]

(0.0, 0.5)

In [86]:
na[0:]

array([1, 2, 3, 4])

In [87]:
na[1:3]

array([2, 3])

In [88]:
na[:-1]

array([1, 2, 3])

In [89]:
na[::2]

array([1, 3])

In [90]:
nb[-1]

2.0

In [91]:
nb[[0, 2, -1]]

array([0., 1., 2.])

---

## Array Types

In [92]:
na

array([1, 2, 3, 4])

In [93]:
nb

array([0. , 0.5, 1. , 1.5, 2. ])

In [94]:
na.dtype

dtype('int32')

In [95]:
nb.dtype

dtype('float64')

#### Set Type

In [96]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [97]:
np.array([1, 2, 3, 4], dtype=np.int64)

array([1, 2, 3, 4], dtype=int64)

In [98]:
nc = np.array(["a", "b", "c"])

In [99]:
nc.dtype

dtype('<U1')

In [100]:
nd = np.array([{"a": 1}, sys])

In [101]:
nd.dtype

dtype('O')

#### Demo

In [102]:
level_list = np.array([1000, 4000, 150, 9001, 1500])
any(level_list > 9000)

True

---

## Dimensions and shapes

#### Demo

In [103]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [104]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
A.shape

(2, 3)

In [106]:
A.ndim

2

In [107]:
A.size

6

---

#### Demo

In [108]:
B = np.array(
    [
        [
            [12, 11, 10],
            [9, 8, 7],
        ],
        [[6, 5, 4], [3, 2, 1]],
    ]
)

In [109]:
B.dtype

dtype('int32')

---

#### Demo
If the shape isn't consistent, it'll just fall back to regular Python objects:



In [110]:
C = np.array(
    [
        [
            [12, 11, 10],
            [9, 8, 7],
        ],
        [[6, 5, 4]],
    ],
    dtype=np.object_,
)

In [111]:
C.dtype

dtype('O')

In [112]:
C.shape

(2,)

In [113]:
C.size

2

In [114]:
type(C[0])

list

---

## Indexing and Slicing of Matrices

In [144]:
# Square matrix
"""
# .  0  1  2
    [1, 2, 3],  # 0
    [4, 5, 6],  # 1
    [7, 8, 9],  # 2
"""
A = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

In [116]:
A[1]

array([4, 5, 6])

In [117]:
# A[d1, d2, d3, d4]
A[1][0]

4

In [118]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [120]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [121]:
A[:2, 2:]

array([[3],
       [6]])

In [126]:
A[1] = np.array([10, 10, 10])
A[2] = 99

In [127]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

---

## Summary Statistics

In [128]:
na

array([1, 2, 3, 4])

In [129]:
na.sum()

10

In [131]:
na.mean()

2.5

- 標準差(std, standard deviation)
- 變異數(var, variance)

In [132]:
a.std()

1.2139539573337679

In [133]:
a.var()

1.4736842105263157

In [136]:
D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [137]:
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
D.sum()

45

In [140]:
D.mean()

5.0

In [141]:
D.std()

2.581988897471611

- axis=None: Apply operation array-wise.
- 
axis=0: Apply operation column-wise, across all rows for each column
- 
axis=1: Apply operation row-wise, across all columns for each row.

In [145]:
D.sum(axis=0)

array([12, 15, 18])

In [147]:
D.sum(axis=1)

array([ 6, 15, 24])

In [149]:
D.mean(axis=0)

array([4., 5., 6.])

In [150]:
D.mean(axis=1)

array([2., 5., 8.])

## Broadcasting and Vectorized operations

In [157]:
ndarr = np.arange(4)

In [158]:
ndarr

array([0, 1, 2, 3])

In [159]:
ndarr + 10

array([10, 11, 12, 13])

In [160]:
ndarr * 10

array([ 0, 10, 20, 30])

In [161]:
ndarr

array([0, 1, 2, 3])

In [164]:
ndarr += 100
ndarr

array([300, 301, 302, 303])

In [165]:
l = [0, 1, 2, 3]

In [166]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [170]:
a = np.arange(4)
b = np.array([10, 10, 10, 10])

In [171]:
a + b

array([10, 11, 12, 13])

## Boolean Arrays

In [203]:
a

array([0, 1, 2, 3])

In [202]:
a[[True, False, False, True]]

array([0, 3])

In [204]:
a >= 2

array([False, False,  True,  True])

In [207]:
a[a >= 2]

array([2, 3])

In [210]:
a[a > a.mean()]

array([2, 3])

In [211]:
a[~(a > a.mean())]

array([0, 1])

## Linear Algebra


---

# Function

## `linspace`

> 在一定範圍內來均勻地撒點

In [124]:
a = np.linspace(1, 3, 3)
print(a)

[1. 2. 3.]


In [125]:
a = np.linspace(1, 5, 20)
print(a)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


---

# Size of objects in Memory



- An integer in Python is > 24bytes
- Longs are even larger
- Numpy size is much smaller

In [181]:
sys.getsizeof(1)

28

In [182]:
sys.getsizeof(10**100)

72

In [184]:
np.dtype(int).itemsize

4

In [183]:
np.dtype(np.int8).itemsize

1

In [185]:
np.dtype(float).itemsize

8

- Lists are even larger



In [186]:
sys.getsizeof([1])

64

In [187]:
np.array([1]).nbytes

4

## Performance

In [199]:
pl = list(range(100000))

In [198]:
na = np.arange(100000)

In [200]:
%time np.sum(na ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [201]:
%time sum([x ** 2 for x in pl])

CPU times: total: 15.6 ms
Wall time: 8 ms


333328333350000